# Development Image:
# This is a devcontainer image for the developent
# environment.

FROM node:14

WORKDIR /app
# COPY package*.json ./
# RUN npm install
COPY . .

# RUN npm build

EXPOSE 3000 8080 80
CMD ["npm", "start"]
